<?php
/** @var \Sebwite\SocialProductQuestions\Block\Tab $block */
// $productUrl = "//$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]";
$product = $block->getProduct();
$productUrl = $block->getProductUrl($product);
$a = 'a';
?>

<div id="disqus_thread"></div>
<script>
    var disqus_config = function () {
        this.page.url = "<?php echo $productUrl; ?>";
        this.page.identifier = "<?php echo $product->getId(); ?>";
    };
    (function() {
        var d = document, s = d.createElement('script');

        s.src = '//<?php echo $block->getData('disqusid'); ?>.disqus.com/embed.js';

        s.setAttribute('data-timestamp', + new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>